package uk.ac.ncl.team15.android.retrofit.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// Auto-generated by: http://www.jsonschema2pojo.org/
public class ModelAuth {

    @SerializedName("user_data")
    @Expose
    private ModelUserData userData;
    @SerializedName("token")
    @Expose
    private String token;

    public ModelUserData getUserData() {
        return userData;
    }

    public String getToken() {
        return token;
    }
}