package uk.ac.ncl.team15.android.retrofit.models;

/**
 * @Purpose: A JSON API response on authentication
 *
 * @authors  Callum
 * @since   1/5/2018
 * extended by @authors
 *
 **/

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// Auto-generated by: http://www.jsonschema2pojo.org/
public class ModelAuth {

    @SerializedName("user_data")
    @Expose
    private ModelUser userData;
    @SerializedName("token")
    @Expose
    private String token;

    public ModelUser getUserData() {
        return userData;
    }

    public String getToken() {
        return token;
    }
}